### Nama : Al Fiana Nur Priyanti <br> NIM : 2109106022

# Posttest KB 7: Pengenalan Tensorflow
## Import Library

In [66]:
import tensorflow as tf

## Instruksi 1: Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [67]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.1337056 , -0.42507994,  1.4856426 , -0.21148287,  3.1926441 ],
       [-0.75514704,  0.7227887 , -0.87344414,  0.528661  ,  1.1474953 ],
       [ 0.1748921 ,  0.07561827,  0.69876033, -0.41548777, -1.7608722 ],
       [ 0.4911833 , -1.8575251 , -0.8524507 , -1.9621029 ,  1.1082697 ],
       [-0.04285634, -0.03267585,  0.61398745, -1.4472647 , -3.0750885 ]],
      dtype=float32)>

## Instruksi 2: Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

tf.float32 = digunakan untuk membuat tipe data tensor sebagai float agar bisa di operasikan dengan variable random_tensor

In [68]:
prime_tensor = tf.constant([[2, 3, 5, 7, 11],
                            [13, 17, 19, 23, 29],
                            [31, 37, 41, 43, 47],
                            [53, 59, 61, 67, 71],
                            [73, 79, 83, 89, 97]
                           ], shape = [5,5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Instruksi 3: Tampilkan dimensi dari dua variabel tersebut.

In [69]:
print(f"""
===========================================
      T E N S O R   D I M E N S I O N
===========================================
 Dimensi Random Tensor = TensorShape{random_tensor.shape}
 Dimensi Prime Tensor  = TensorShape{prime_tensor.shape}
""")


      T E N S O R   D I M E N S I O N
 Dimensi Random Tensor = TensorShape(5, 5)
 Dimensi Prime Tensor  = TensorShape(5, 5)



## Instruksi 4: Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [70]:
###### Penjumlahan Tensor
jumlah = random_tensor + prime_tensor

# Pengurangan Tensor
kurang = random_tensor - prime_tensor

# Perkalian Tensor
kali = random_tensor * prime_tensor

# Pembagian Tensor
bagi = random_tensor / prime_tensor

# Sisa Bagi Tensor
sisa_bagi = random_tensor % prime_tensor

#Pembagian Bulat Tensor
bagi_bulat = random_tensor // prime_tensor

#Pemangkatan Tensor
pangkat = random_tensor ** prime_tensor

#Logaritma Tensor
log = tf.math.log(random_tensor, prime_tensor)


print(f"""
=========================================================================
             H A S I L   O P E R A S I   A R I T M A T I K A
=========================================================================
                          P e n j u m l a h a n
=========================================================================
{jumlah}

=========================================================================
                          P e n g u r a n g a n
=========================================================================
{kurang}

=========================================================================
                            P e r k a l i a n
=========================================================================
{kali}

=========================================================================
                            P e m b a g i a n
=========================================================================
{bagi}

=========================================================================
                            S i s a   B a g i
=========================================================================
{sisa_bagi}

=========================================================================
                      P e m b a g i a n   B u l a t 
=========================================================================
{bagi_bulat}

=========================================================================
                          P e m a n g k a t a n
=========================================================================
{pangkat}

=========================================================================
                            L o g a r i t m a
=========================================================================
{log}
""")


             H A S I L   O P E R A S I   A R I T M A T I K A
                          P e n j u m l a h a n
[[ 3.1337056  2.5749202  6.4856424  6.788517  14.192644 ]
 [12.244853  17.722788  18.126556  23.528662  30.147495 ]
 [31.174892  37.07562   41.69876   42.58451   45.23913  ]
 [53.491184  57.142475  60.14755   65.037895  72.10827  ]
 [72.957146  78.96732   83.61399   87.552734  93.92491  ]]

                          P e n g u r a n g a n
[[  -0.8662944   -3.4250798   -3.5143576   -7.211483    -7.807356 ]
 [ -13.755147   -16.277212   -19.873444   -22.471338   -27.852505 ]
 [ -30.825108   -36.92438    -40.30124    -43.41549    -48.76087  ]
 [ -52.508816   -60.857525   -61.85245    -68.962105   -69.89173  ]
 [ -73.042854   -79.03268    -82.38601    -90.447266  -100.07509  ]]

                            P e r k a l i a n
[[   2.2674112   -1.2752398    7.4282126   -1.48038     35.119087 ]
 [  -9.816912    12.287408   -16.595438    12.159204    33.277363 ]
 [   5.421655     2.797876

## Instruksi 5: Tampilkan nilai maksimum dan minimum dari variable random_tensor.

tf.argmax() = digunakan untuk mengkalkulasi nilai maksimum <br>
tf.argmin() = digunakan untuk mengkalkulasi nilai minimum

In [71]:
#Lokasi Nilai Maksimum Random Tensor berdasarkan kolom
max0_random_tensor = tf.argmax(random_tensor, axis = 0)

#Lokasi Nilai Maksimum Random Tensor berdasarkan baris
max1_random_tensor = tf.argmax(random_tensor, axis = 1)

#Lokasi Nilai Minimum Random Tensor berdasarkan kolom
min0_random_tensor = tf.argmin(random_tensor, axis = 0)

#Lokasi Nilai Minimum Random Tensor berdasarkan baris
min1_random_tensor = tf.argmin(random_tensor, axis = 1)

print(f"""
===========================================
 L O K A S I   N I L A I   M A K S I M U M
         R A N D O M   T E N S O R 
===========================================
    Berdasarkan Kolom = {max0_random_tensor}
    Berdasarkan Baris = {max1_random_tensor}
""")

print(f"""
===========================================
  L O K A S I   N I L A I   M I N I M U M
         R A N D O M   T E N S O R 
===========================================
    Berdasarkan Kolom = {min0_random_tensor}
    Berdasarkan Baris = {min1_random_tensor}
""")


 L O K A S I   N I L A I   M A K S I M U M
         R A N D O M   T E N S O R 
    Berdasarkan Kolom = [0 1 0 1 0]
    Berdasarkan Baris = [4 4 2 4 2]


  L O K A S I   N I L A I   M I N I M U M
         R A N D O M   T E N S O R 
    Berdasarkan Kolom = [1 3 1 3 4]
    Berdasarkan Baris = [1 2 4 3 4]



## Instruksi 6: Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation).

tf.concat() = digunakan untuk menggabungkan variabel

In [72]:
concat = tf.concat([random_tensor, prime_tensor], axis = 0)

print(f"""
=============================================================
                   C O N C A T E N A T I O N 
=============================================================
{concat}
""")


                   C O N C A T E N A T I O N 
[[ 1.1337056e+00 -4.2507994e-01  1.4856426e+00 -2.1148287e-01
   3.1926441e+00]
 [-7.5514704e-01  7.2278869e-01 -8.7344414e-01  5.2866101e-01
   1.1474953e+00]
 [ 1.7489210e-01  7.5618275e-02  6.9876033e-01 -4.1548777e-01
  -1.7608722e+00]
 [ 4.9118331e-01 -1.8575251e+00 -8.5245073e-01 -1.9621029e+00
   1.1082697e+00]
 [-4.2856343e-02 -3.2675847e-02  6.1398745e-01 -1.4472647e+00
  -3.0750885e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]]



## Instruksi 7: Tampilkan hasil sorting dari kedua variable di atas (descending).

tf.sort() = digunakan untuk mengurutkan tensor

In [74]:
#Sorting Random Tensor
sort_random_tensor = tf.sort(random_tensor, direction="DESCENDING")

#Sorting Prime Tensor
sort_prime_tensor = tf.sort(prime_tensor, direction="DESCENDING")

print(f"""
===============================================================
           S O R T I N G   R A N D O M   T E N S O R 
===============================================================
{sort_random_tensor}
""")

print(f"""
===============================================================
            S O R T I N G   P R I M E   T E N S O R 
===============================================================
{sort_prime_tensor}
""")


           S O R T I N G   R A N D O M   T E N S O R 
[[ 3.1926441   1.4856426   1.1337056  -0.21148287 -0.42507994]
 [ 1.1474953   0.7227887   0.528661   -0.75514704 -0.87344414]
 [ 0.69876033  0.1748921   0.07561827 -0.41548777 -1.7608722 ]
 [ 1.1082697   0.4911833  -0.8524507  -1.8575251  -1.9621029 ]
 [ 0.61398745 -0.03267585 -0.04285634 -1.4472647  -3.0750885 ]]


            S O R T I N G   P R I M E   T E N S O R 
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]

